#pragma once

#include <string>
#include <vector>
#include <memory>
#include <functional>
#include "storage/schema.h"
#include "common/flexql_types.h"

namespace flexql {
namespace storage {

constexpr size_t PAGE_SIZE = 4096;
constexpr size_t PAGE_HEADER_SIZE = 9;

struct Page {
    uint32_t page_id;
    uint16_t row_count;
    uint16_t free_offset;
    uint8_t flags;
    uint8_t data[PAGE_SIZE - PAGE_HEADER_SIZE]; 
};

// Allocate a zeroed in-memory Page
std::unique_ptr<Page> page_alloc(uint32_t page_id);

// Check if page has space for a row of given size (including the 2-byte length prefix)
bool page_has_space(const Page* page, size_t row_size);

// Write row bytes at free_offset. Returns slot_index.
int page_write_row(Page* page, const std::vector<uint8_t>& row_data);

// Read row at slot_index
bool page_read_row(const Page* page, int slot_index, std::vector<uint8_t>& row_out);


class StorageEngine {
public:
    StorageEngine(const std::string& table_name, const std::string& data_dir, std::shared_ptr<Schema> schema);
    ~StorageEngine();

    bool open();
    void close();
    void flush() {
        if (fd_ >= 0) {
            for (size_t i = 0; i < pages_.size(); ++i) {
                flush_page(i);
            }
        }
    }

    // Appends row and returns disk offset. 
    // Offset structure: (page_id * PAGE_SIZE) + page_byte_offset
    uint64_t insert_row(const Row& row);

    // Inserts all rows sequentially, flushes dirty pages once at the end.
    // Returns a vector of disk offsets (one per row, in insertion order).
    std::vector<uint64_t> bulk_insert_rows(const std::vector<flexql::Row>& rows);
    
    // Iterates all pages and all rows, invoking callback
    void scan(std::function<bool(const Row&)> callback);
    
    // Reads row directly given offset generated by insert_row
    bool read_row_at_offset(uint64_t offset, Row& row_out);

private:
    std::string file_path_;
    std::shared_ptr<Schema> schema_;
    int fd_ = -1;
    
    std::vector<std::unique_ptr<Page>> pages_;
    
    std::vector<uint8_t> serialize_row(const Row& row);
    Row deserialize_row(const std::vector<uint8_t>& data);
    
    void load_pages();
    void flush_page(size_t page_idx);
};

std::unique_ptr<StorageEngine> storage_open(const std::string& table_name, const std::string& data_dir, std::shared_ptr<Schema> schema);

} // namespace storage
} // namespace flexql
